### ISSUE TITLE
Error: When executing the make or npm start

### ISSUE THREAD

**Issue by zjx-immersion** [codeskyblue/gohttp#7]
Hi 
当我本地运行make dev或者npm start的时候报错， 我的机器是mac,错误信息如下，是怎么回事呢，应该是打包style.css的时候出错了

ERROR in ./~/css-loader!./public/css/style.css

Module build failed: ReferenceError: Promise is not defined
    at LazyResult.async (/Users/jxzhong/GoProject2/FirstGo/src/github.com/codeskyblue/gohttp/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:152:31)
    at LazyResult.then (/Users/jxzhong/GoProject2/FirstGo/src/github.com/codeskyblue/gohttp/node_modules/css-loader/node_modules/postcss/lib/lazy-result.js:75:21)
    at processCss (/Users/jxzhong/GoProject2/FirstGo/src/github.com/codeskyblue/gohttp/node_modules/css-loader/lib/processCss.js:174:5)
    at Object.module.exports (/Users/jxzhong/GoProject2/FirstGo/src/github.com/codeskyblue/gohttp/node_modules/css-loader/lib/loader.js:22:2)
 @ ./public/css/style.css 4:14-79 13:2-17:4 14:20-85
webpack: bundle is now VALID.

**Comment by codeskyblue** [comment]
有没有运行 `npm install`

**Comment by zjx-immersion** [comment]
运行了 npm install的

➜  gohttp git:(master) npm install
npm WARN package.json @ No repository field.
npm WARN package.json babel-core@5.8.34 No README data

**Comment by codeskyblue** [comment]
I've tested in another machine, but everything goes fine.

**Comment by zjx-immersion** [comment]
好了 Thanks,  升级了node到最新版就Ok了
